[character]
error_symbol = "[✗](bold red)"

[directory]
read_only = " 🔒"

[cmd_duration]
format = "[$duration]($style) "

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
